version: '3.8'
services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: hidden-gem-db
    environment:
      POSTGRES_DB: hiddenGem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: hidden-gem-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: hidden-gem-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
  esdata:
